//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LawFirmDbContext : DbContext
    {
        public LawFirmDbContext()
            : base("name=LawFirmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NRBM_ADVERSELAWYER> NRBM_ADVERSELAWYER { get; set; }
        public DbSet<NRBM_ADVERSELAWYERHISTORY> NRBM_ADVERSELAWYERHISTORY { get; set; }
        public DbSet<NRBM_APPOINTMENT> NRBM_APPOINTMENT { get; set; }
        public DbSet<NRBM_APPOINTMENTHISTORY> NRBM_APPOINTMENTHISTORY { get; set; }
        public DbSet<NRBM_CASE> NRBM_CASE { get; set; }
        public DbSet<NRBM_CASEHISTORY> NRBM_CASEHISTORY { get; set; }
        public DbSet<NRBM_CLIENT> NRBM_CLIENT { get; set; }
        public DbSet<NRBM_CLIENTHISTORY> NRBM_CLIENTHISTORY { get; set; }
        public DbSet<NRBM_COUNSELS> NRBM_COUNSELS { get; set; }
        public DbSet<NRBM_COUNSELSHISTORY> NRBM_COUNSELSHISTORY { get; set; }
        public DbSet<NRBM_COURTAPPEARANCE> NRBM_COURTAPPEARANCE { get; set; }
        public DbSet<NRBM_COURTAPPEARANCEHISTORY> NRBM_COURTAPPEARANCEHISTORY { get; set; }
        public DbSet<NRBM_LAWYER> NRBM_LAWYER { get; set; }
        public DbSet<NRBM_LAWYERHISTORY> NRBM_LAWYERHISTORY { get; set; }
        public DbSet<NRBM_LITIGATES> NRBM_LITIGATES { get; set; }
        public DbSet<NRBM_LITIGATESHISTORY> NRBM_LITIGATESHISTORY { get; set; }
        public DbSet<NRBM_PHONE> NRBM_PHONE { get; set; }
        public DbSet<NRBM_PHONEHISTORY> NRBM_PHONEHISTORY { get; set; }
        public DbSet<NRBM_SETS> NRBM_SETS { get; set; }
        public DbSet<NRBM_STAFF> NRBM_STAFF { get; set; }
        public DbSet<NRBM_STAFFHISTORY> NRBM_STAFFHISTORY { get; set; }
        public DbSet<NRBM_WORKSFOR> NRBM_WORKSFOR { get; set; }
        public DbSet<NRBM_WORKSFORHISTORY> NRBM_WORKSFORHISTORY { get; set; }
    }
}
