//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class LawFirmDbContext : DbContext
    {
        public LawFirmDbContext()
            : base("name=LawFirmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NRBM_ADVERSELAWYER> NRBM_ADVERSELAWYER { get; set; }
        public DbSet<NRBM_ADVERSELAWYERHISTORY> NRBM_ADVERSELAWYERHISTORY { get; set; }
        public DbSet<NRBM_APPOINTMENT> NRBM_APPOINTMENT { get; set; }
        public DbSet<NRBM_APPOINTMENTHISTORY> NRBM_APPOINTMENTHISTORY { get; set; }
        public DbSet<NRBM_CASE> NRBM_CASE { get; set; }
        public DbSet<NRBM_CASEHISTORY> NRBM_CASEHISTORY { get; set; }
        public DbSet<NRBM_CLIENT> NRBM_CLIENT { get; set; }
        public DbSet<NRBM_CLIENTHISTORY> NRBM_CLIENTHISTORY { get; set; }
        public DbSet<NRBM_COUNSELS> NRBM_COUNSELS { get; set; }
        public DbSet<NRBM_COUNSELSHISTORY> NRBM_COUNSELSHISTORY { get; set; }
        public DbSet<NRBM_COURTAPPEARANCE> NRBM_COURTAPPEARANCE { get; set; }
        public DbSet<NRBM_COURTAPPEARANCEHISTORY> NRBM_COURTAPPEARANCEHISTORY { get; set; }
        public DbSet<NRBM_LAWYER> NRBM_LAWYER { get; set; }
        public DbSet<NRBM_LAWYERHISTORY> NRBM_LAWYERHISTORY { get; set; }
        public DbSet<NRBM_LITIGATES> NRBM_LITIGATES { get; set; }
        public DbSet<NRBM_LITIGATESHISTORY> NRBM_LITIGATESHISTORY { get; set; }
        public DbSet<NRBM_PHONE> NRBM_PHONE { get; set; }
        public DbSet<NRBM_PHONEHISTORY> NRBM_PHONEHISTORY { get; set; }
        public DbSet<NRBM_SETS> NRBM_SETS { get; set; }
        public DbSet<NRBM_STAFF> NRBM_STAFF { get; set; }
        public DbSet<NRBM_STAFFHISTORY> NRBM_STAFFHISTORY { get; set; }
        public DbSet<NRBM_WORKSFOR> NRBM_WORKSFOR { get; set; }
        public DbSet<NRBM_WORKSFORHISTORY> NRBM_WORKSFORHISTORY { get; set; }
        public DbSet<NRBM_APTVIEW> NRBM_APTVIEW { get; set; }
    
        public virtual int NRBM_PROC_DELETEADVERSELAWYER(Nullable<decimal> aDLAW_ID)
        {
            var aDLAW_IDParameter = aDLAW_ID.HasValue ?
                new ObjectParameter("ADLAW_ID", aDLAW_ID) :
                new ObjectParameter("ADLAW_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NRBM_PROC_DELETEADVERSELAWYER", aDLAW_IDParameter);
        }
    
        public virtual int NRBM_PROC_DELETECASE(Nullable<decimal> cASE_CASEID)
        {
            var cASE_CASEIDParameter = cASE_CASEID.HasValue ?
                new ObjectParameter("CASE_CASEID", cASE_CASEID) :
                new ObjectParameter("CASE_CASEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NRBM_PROC_DELETECASE", cASE_CASEIDParameter);
        }
    
        public virtual int NRBM_PROC_DELETECLIENT(Nullable<decimal> cLIENT_CID)
        {
            var cLIENT_CIDParameter = cLIENT_CID.HasValue ?
                new ObjectParameter("CLIENT_CID", cLIENT_CID) :
                new ObjectParameter("CLIENT_CID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NRBM_PROC_DELETECLIENT", cLIENT_CIDParameter);
        }
    
        public virtual int NRBM_PROC_DELETELAWYER(Nullable<decimal> lAWYER_LAWID)
        {
            var lAWYER_LAWIDParameter = lAWYER_LAWID.HasValue ?
                new ObjectParameter("LAWYER_LAWID", lAWYER_LAWID) :
                new ObjectParameter("LAWYER_LAWID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NRBM_PROC_DELETELAWYER", lAWYER_LAWIDParameter);
        }
    
        public virtual int NRBM_PROC_DELETESTAFF(Nullable<decimal> sTAFF_SID)
        {
            var sTAFF_SIDParameter = sTAFF_SID.HasValue ?
                new ObjectParameter("STAFF_SID", sTAFF_SID) :
                new ObjectParameter("STAFF_SID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NRBM_PROC_DELETESTAFF", sTAFF_SIDParameter);
        }
    }
}
