//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_SETS
    {
        public int SETSID { get; set; }
        public Nullable<int> STAFFID { get; set; }
        public Nullable<int> APTID { get; set; }
        public Nullable<System.DateTime> DATESET { get; set; }
    
        public virtual NRBM_APPOINTMENT NRBM_APPOINTMENT { get; set; }
        public virtual NRBM_STAFF NRBM_STAFF { get; set; }
    }
}
