//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_CLIENT
    {
        public NRBM_CLIENT()
        {
            this.NRBM_APPOINTMENT = new HashSet<NRBM_APPOINTMENT>();
            this.NRBM_CASE = new HashSet<NRBM_CASE>();
            this.NRBM_COUNSELS = new HashSet<NRBM_COUNSELS>();
            this.NRBM_COURTAPPEARANCE = new HashSet<NRBM_COURTAPPEARANCE>();
        }
    
        public int CLIENTID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string BUSNAME { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<NRBM_APPOINTMENT> NRBM_APPOINTMENT { get; set; }
        public virtual ICollection<NRBM_CASE> NRBM_CASE { get; set; }
        public virtual ICollection<NRBM_COUNSELS> NRBM_COUNSELS { get; set; }
        public virtual ICollection<NRBM_COURTAPPEARANCE> NRBM_COURTAPPEARANCE { get; set; }
    }
}
