//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_APPOINTMENT
    {
        public NRBM_APPOINTMENT()
        {
            this.NRBM_SETS = new HashSet<NRBM_SETS>();
        }
    
        public int APTID { get; set; }
        public Nullable<int> LAWID { get; set; }
        public Nullable<int> CASEID { get; set; }
        public Nullable<int> CLIENTID { get; set; }
        public Nullable<System.DateTime> DATEON { get; set; }
        public string LOCATION { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual NRBM_CASE NRBM_CASE { get; set; }
        public virtual NRBM_CLIENT NRBM_CLIENT { get; set; }
        public virtual NRBM_LAWYER NRBM_LAWYER { get; set; }
        public virtual ICollection<NRBM_SETS> NRBM_SETS { get; set; }
    }
}
