//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_COUNSELS
    {
        public int COUNSELSID { get; set; }
        public int LAWID { get; set; }
        public int CLIENTID { get; set; }
        public string SDATE { get; set; }
        public string EDATE { get; set; }
        public Nullable<decimal> HOURS { get; set; }
        public string FEES { get; set; }
    }
}
