//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_WORKSVIEW
    {
        public int WORKID { get; set; }
        public int STAFFID { get; set; }
        public int LAWID { get; set; }
        public string SFNAME { get; set; }
        public string SLNAME { get; set; }
        public string LFNAME { get; set; }
        public string LLNAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> ENDDATE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> HOURS { get; set; }
    }
}
