//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_SETSVIEW
    {
        public int SETSID { get; set; }
        public int STAFFID { get; set; }
        public int APTID { get; set; }
        public string SFNAME { get; set; }
        public string SLNAME { get; set; }
        public Nullable<System.DateTime> SETDATE { get; set; }
    }
}
