//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_PHONEHISTORY
    {
        public int PHONEID { get; set; }
        public Nullable<int> CLIENTID { get; set; }
        public string HOME { get; set; }
        public string CELL { get; set; }
        public string BUSINESS { get; set; }
        public Nullable<System.DateTime> DATEDELETED { get; set; }
    }
}
