//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLawFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NRBM_ADVERSELAWYER
    {
        public NRBM_ADVERSELAWYER()
        {
            this.NRBM_COURTAPPEARANCE = new HashSet<NRBM_COURTAPPEARANCE>();
            this.NRBM_LITIGATES = new HashSet<NRBM_LITIGATES>();
        }
    
        public int ADLAWID { get; private set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public string FullName { get { return FNAME + " " + LNAME; } set { FNAME = FNAME; } }
    
        public virtual ICollection<NRBM_COURTAPPEARANCE> NRBM_COURTAPPEARANCE { get; set; }
        public virtual ICollection<NRBM_LITIGATES> NRBM_LITIGATES { get; set; }
    }
}
